/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
export const ssr = false;

const Model = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/cupula.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="NurbsPath001"
          position={[0, 1.8, -3.27]}
          rotation={[0, 1.33, 0]}
          scale={[1.44, 1, 1.03]}
        >
          <group
            name="Sphere003"
            position={[-2.61, -0.35, 0.76]}
            rotation={[-2.39, 0.03, -1.49]}
            scale={[0.98, 0.7, 0.98]}
          >
            <mesh
              name="Sphere006"
              castShadow
              receiveShadow
              geometry={nodes.Sphere006.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              name="Sphere006_1"
              castShadow
              receiveShadow
              geometry={nodes.Sphere006_1.geometry}
              material={materials.bola}
            />
            <mesh
              name="Sphere006_2"
              castShadow
              receiveShadow
              geometry={nodes.Sphere006_2.geometry}
              material={materials["Material.003"]}
            />
          </group>
        </group>
        <mesh
          name="Sphere"
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials["Material.001"]}
          position={[0, -4.7, 0.26]}
          scale={2}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/cupula.glb");
export default Model;

 
   
    
 
  